apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:DodjWaoHrZ2TaayX2TRa9FTqUuazIHU35Gh0y9UBPFH4yl6NVwQbmwmSr2br869Ay3/gF3RA+BGpU3/uq9yoaDPtS2dwI7eGJJMWCPt/lrkuSwsB/mrTsM/8b00LxRt1TOmVhwxveg7Gd+nOksdvumBI86MPbbFa2xd0cLRcGVRZ0/g235sVyUI8XehGRYVUfHMd+saakZ2SwUDCwzpmmk6wMFMuJkLdNeNYs7ivgq0/yqkf8qQVNJP4uD6Hs56UQuAucZNi2L+NflCK6dkPwHrTeoMCveAGAlYZsDR2BAnS4J2rQXEWPKRfHCI=,iv:qrnYkAVuikFW4M4g++1j6oXP+7qb5s9mD2gfOiY4i2A=,tag:muceR9c3y+y65FQDayUzwg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSnVuNm1DZi8rLzR2NmxI
            NFBsUkoxNmFXNG1UMldXK2kzYnhYRVR4MDJzClZ6cGFpRlRhc0dkTmdLOXpXVERY
            bnFScHpsckg0aXNjVU1SeTNrMGVoblkKLS0tIG84OGR3andsYThhczdQV2VaRTIx
            c0FzR0hWTExBTGMxRTZ3WkF4S0g4UU0Ks2SksV+uBNoFTzNCn3GnE63Uz2nvwAX7
            bRQsi/OR/alQlp4rGP2dahLU6e7N45SE/A9GFekk6sqyh5axhk5gSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T07:34:31Z"
    mac: ENC[AES256_GCM,data:M7zTv0Kx23am0oTJ2DIy8ZUxAOud4iFiLhL0MYJJQJRyn8l189Fd7YBHEB2amHsRfLn1jn3EDV3c69OM8OtOqtHPotV3ZnCfkMdbLiXNw4CCN+nnBd3q1R+5u5qjQINvswjHRSxt0AqRmju+y9Zssq4B9e6Hpcwa/XealK9f2vs=,iv:69RpBOkSrIZfebPKrzC3zJc+1edp9m9BhaPcQDROvOc=,tag:HwKp3IO6jIjDGAEntqZwDQ==,type:str]
    version: 3.13.3
