apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:a7iJHJ7R0g2d40Qhkl3/EDXtz9qNy102kmnCEFwvanVZlKGkSWUQikOIzxGrreQpYY8VkZqZQz21d9Zwrt3nmkeOX91d8Qh6hgEq2LruQin7ty+otmJlCde8kBQF0T3WFO5lLRRMcDrkFd3IzCmQ+DN8tFpcqD1vUeSrCWlIXEVD4pCrtvjgeRNpv8Jxt7pxPPzEU86FnhQEH1MF9QLLwcmE+IMdRPhFc8rHNRgv32YCZZQVFo0Lp5FJzI0cSWiPhNO7QwIunctDWbqWMU97KYiTJARIiHaUX5kl/aMZxe+3MIndAnULyvhuiqE=,iv:1K34MXg7T2JSUS78RsqSnAiS49nhVmUFJ5JXsqSBUZA=,tag:M0GxOpSUm7lVk/IPu8udFw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcitNR2Y3UFRGc0g4WXpG
            M2IxcytUVEdFNGtLekF4ek9CdklWUHd0SlgwCmpQTXRuU3dodVZaQVpYN0JRakZm
            ZXdKQ1NKejUxWXNVMm45OVM5eFpVL1EKLS0tIEpoc2haM1EyT0hrQ2RjRUtMMy9q
            dFNHUU13WnQ1dndKNkdIZi9ORHUzbzAKsoWq1lkofLx1e+7cL06S8JT4nHK08aJM
            4XDb5iL7JsVD6h+q5HQ2/V1oQSQNR9pdY+hzF6HZabLQ8U4imurl5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T09:02:19Z"
    mac: ENC[AES256_GCM,data:MSMnzyOqJCcCwtNpKkTcK6MeG/eQ0tQxMVL13TGYvcJPSMHWnBr11J5u3vOhb2tbQ/GRXJ2AELcdFOMqlQ82dtI+OJzJ49vH0QZeKiuv8Ov07YlF1SO0iy1FctGn3rNdIwxSZiaQLhfdPi33pCexmIEWEXnZLt+nsbSGFKddqf4=,iv:0W+cPQfaWXN1kMl4Y2BWyewpKy5ZxpOOD3y+wVAeywQ=,tag:m7ilIzCyeNZ1sIeB4W9TAA==,type:str]
    version: 3.13.3
