apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RsRS3ZRbRk6w44hT83wmkj4d7sRD+5sEqo60PLqdYfE65xQN61IGCXPKjBGc7fhELdejOjopkmZourIKaAjD+LXgMucSlK7HfwM80z5a6WpPfQEIBuPZZ8cXl9DRXsQMY/Y1uleQ/sEKxpAaFSWtk27/AB77b51PiqRRTkObQWp74x1iWPkHg64ztcvaClqbuerXsitUR66QGM4fYWnYNHmZcJDRSXoMhAj1keKbG9lCF5n/CDvbFaW+Ueo3QI3qaGAIabPmjk0D3d+9kwN1Yd8vahhwNeXoNQEumeoptVdmzK/jTwefJwojs/o=,iv:4WbZVU1jv7Usn8ObUxALKXWWwKSpP4y0HmMpBTU2KuU=,tag:zNYubU/rv2PKMyMn4K1nuQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeTFGRXI4T3N5WkduRC8y
            VXZBYTl5SVhGWUdDcFJrWjh1TWlxd3VuWEJNCnNHMENyYmtleHREK1ROQUpFRVNS
            N0RFUnAwNldaZFkrWjJYL0NKV3RxU00KLS0tIDZxZWVmSmF0Tm5wc3BoWGN2OEJm
            RGtlajlBQU1mWlU3dnZmZXE5bFFnaEkKQAdSr1e+5Lnd+ZrR2uqW4YUcccRQ2ctn
            A88lPfo4pe+tK5FiTzoMUGZB7HtyzlqMtkmcfnNkF8eYJ/aiGRphQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T07:49:45Z"
    mac: ENC[AES256_GCM,data:0WSWZpIe2IMNrbFw4VHNgC8BXoHHoWikmUyYT8cGhD+7YGOIJWjsU+EwzJB4C6+cH/H7PIOWha8jV4A74zDKSyQ8RejEpR+6ZldZIHA4CwZKIow7rfiJXdGOUnZp36z+q22TaKUjjhDxBLKsEFVMM4L7yeBElJ2v8bnbyvNSUSM=,iv:0FNrAdoA8Mx6R1Kfj5MzjNBx0+eZT9LjQegFHXSh0vE=,tag:SQy+k5rW1LuY6Q7SV5PGpw==,type:str]
    version: 3.13.3
