apiVersion: ENC[AES256_GCM,data:Q3w=,iv:b+PawZdP1pBqxNd6YdicicbQMm/+ZNz4k83Smg/0oYg=,tag:T4fbeuoETJXHZzNBX/QtiQ==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:sO8TeEYyTomfwxPpc5cy7ramhDhlO2XP1hhkZwMDw+Tm/45AwQVRS3yxQkfUhvmds1erMt+5ca60O2zTLxi/fPyUidcjmNmWgkjJNeXO5ZzhwuMfE95FHpD5Q2h8jh92NwchG/Z66cAF+CdvH4lJGUbK2xOpAhSfJqMeafmOXlM2WooS8D0GU/9vWDw1HVjvZiA8tcTzZt0E+jghHeeLopqVrLPtVmT7RoNkFGGYYveeR8fuw4ghJ8DTzNrb3G9PULzEuiVI8xfwt5qGdd6mW+G8n9oypvd39BEoBncMogxkOEt2TB33ebnTDus=,iv:a+2AUAZbNBK9qPndE/D7vYqqCjpT6BGeOLlVm7YTuEQ=,tag:LZnH1qvcTZKVZhQ+eIQiMg==,type:str]
kind: ENC[AES256_GCM,data:mLF+QTQ9,iv:/xPOrWJvf+p22+O1NWuFgRogc5zbACKFCzo6FsuC08Y=,tag:o85ro6zdewAQCrxWVmdc1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Vgdnmz9983EHacdbOm7+xq/z,iv:kMnflU+ukvnd0rM/RKbm9Aiowswvfv+rzeEGenGfhI8=,tag:uxB6qgl0RH3asSz8rYEYAA==,type:str]
    namespace: ENC[AES256_GCM,data:Brc1QH8CGN0=,iv:lRkq31eo0bK81pGyI/Emvx2kpMsEduBXSqv4kD252O0=,tag:rHEJeiNxsBDrOL2dPrXZhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TUV2Qmd0U01qdHpDUUFW
            OGJvRVg2WEZKSDhSKzdBbFhFWS9pb2R2cFZJCmZteldVSXNMRnZZaWVpZGQ1ekZq
            bW1PeGhtMEhiL3NoYXI4NW03RUp3WHMKLS0tIGxOK2xqckhBMTNRRW5FMHY4TDBR
            VDE5RTBjaEVaSUdHM3NtaE5rNXVZMk0KpbWJY6ByiMccCHsF4kqRW0MgvIffUKew
            F9dpsO+KJ2RTKWM+FsXx4szmh9YjugccmLEbZ0ZU2Qjpor08VTpGSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    lastmodified: "2026-09-12T09:16:17Z"
    mac: ENC[AES256_GCM,data:OlF/0ZxfJ3hkXOxRVMfV09NhGxMfidTRMIdGcTPCc6tIL7dwQBNZXQ4kEi+rTCNuXu4AQc6kkWfKlC2boMpii8pEm6fzs5cKUTaPTAVFuYRoCvpFOhRQecBCFNkVL2tHMEWCjOH5labspFXbVXvGimBzMhTJSazaW+L9W/sfTfs=,iv:0oGYyW7OvYZ92QZRHBgU8lgNEHjsg5FQ2k519MXEF+w=,tag:EqZeqBMOSwg92c5W+AOYcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
