apiVersion: ENC[AES256_GCM,data:wg4=,iv:Sl8QoXk9/5LLajLEYbnfK5Q6OoWHQUM90N1k5Ho9NZA=,tag:YVvploqtSNUBOdW4KY4hFg==,type:str]
data:
    credentials.json: ENC[AES256_GCM,data:C6Y9Ajk7lbN/0fAImk7YQ2+3FwvNRnmtMFJeuV2FGiNCk69gL/Te6IdLDzfMrvYdpdjyJ9lNhaXvDMDo6vM9Hn3Qneiw8paDkynoKhiqHhG8anYqF2HMUolHrsnPPoLegegNnEFdR6F5HkyUWA6rukyxqlas1p6W5Fs4U1+hrdfEhJdh5lpiXENtEDV7kCTuzQLBeiQHjv9CvhauQSbsi/H8m46cseR958Rm+IbeFt70MPwyJhy+FJLxNF5gtzTjZqmet9hN0TcfVK9d8LyvZIh7PzfPF829baI5Y1t0Ar26iDzjEWzbcCjJg7U=,iv:saDauaUCETfh0fNwou39I+pBBdO3c0PbcjmQMtD/QUI=,tag:HGOwdLqXgk1CCZvnF77GwQ==,type:str]
kind: ENC[AES256_GCM,data:vjBgu2sj,iv:0GtjHJ85ALiWIVh2y5zbK9uHQkmwGw/EE+iJvUNGU3I=,tag:N0oAPlNquYRkMCdOEGyA3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oTC8IalaF+Qe7ZQfauJDuMT1,iv:LPOYtquI6rcRsHdqv+bx3fHszGMWKgbmM0ISacwnG70=,tag:L+FNvb+/y/g8nn/KIh8W/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQnNZNHZZL2grTFA4aThB
            TTJCZHltQUd6aGQ2d1d5a2pIa0t4WFo4SUFNCnVDengwN0ZTL0MrMWtpeEp1VlNL
            MC93TXpPOW5WRFFSbXd6NVh5cXJQbzgKLS0tIGt1NFFxM2tLUXM3UnptS2E3S1V5
            bGZoeFk5OTFhQlBBcjVaN3dYOVBWSTgKA7mTpYnHSgbBL2YKoRN69RQq2c+MBkgA
            ath8x9F7yedXvXrNRHPC9+4wBcC3exyWJPLdPCxBsvV+YK91+gn2EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    lastmodified: "2026-09-12T09:08:15Z"
    mac: ENC[AES256_GCM,data:h/EoFSk1DtkZSr1cqgFu9299lj6+eBbZXnNkIkzq5OUStpNpUCEvpdPvs2Z3YmWcjUnYKC87k9kR4tBoO7GZNqbRu1+1nhlNxuPZBdvSO5N6m695eM/q2Y5ZJAdeJ8vzr8KP3uYmFzR/OuoaFf0lGLBH5v40H0s1QkiAHsmyWVE=,iv:pUd+nPjdJBvRaVjCKvg6RjyEkPE3Y5rKSEYJ5eMSVnU=,tag:fE+fnebhed291EWtiW4PwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
