apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:fCv2WeazDptlzh2WY5r6qlcdR74KEST4vjfTLYQFELkcgtRgfzNcqq7eELq1VH5410ttPIuHUlam9CBCnOE5SHEf2cPY3PQxdGbNhPd/htibsCX0sgagu7TifvR64NsFxPyoN4eBKPnG40oel7ufBzRiv1FMnTM9+F9ZvEL6CbbNSynTKbIMVsp8GK4kDypPrzlXbwr674oGAUjDOjQ/FPCtmFTzzb3FANcq+BuptZyYgPEQcX6Gt3cxcAopMY+zzzexN+68+v54GnPnlzbk1lDAt2UTy9sjJY8GC1qYn7luuo0ViXxSn+aI3hU=,iv:8YyeLJImwwjykegWadhlI+9syAJYIubfX9aBoZu3+5w=,tag:pLL6mrfkMQ6kEADlYcKXwQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVUdTVmZNQ0lXMWpLTHpM
            UEh4QXlLMkJ3U1V4d2hmSUZQZ1I5dWh5d0cwCkxyUUptM29RVGhUbnZsdStJU1oy
            N0czNnN4SE95ZGYrc2FCNFk4a0pRTDAKLS0tIE9CNmh0Z1lVaWVESXE3ejU3Kzc2
            QlUxcm16K1JkTVRUb2c5dTA5OE55aU0KRIZ9BG0SbLt0s49rtPGa4WvxTKGAo8Ju
            fSYzhwfQwgFSVo92Ymq5xONhhITQTXoPLb1Vi3iRkWvP9awTWjXrLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T10:01:40Z"
    mac: ENC[AES256_GCM,data:sK2VxRyT1YcZdI6p6VM3nwIfw35sA9/qMcf2iCyEcbXRJ2uBI63deLrJKCcyJR0fqCJU+Ppxyd2u6FYYy84cSxCG+HYXw2URQymDgHXzTYCKFVcgwN7BeTdV1gglCsBU/2fLpAVSlIbbc7ol686ywaDR3uDBnlcpBUzy++nHYXQ=,iv:3VgibHn5AuFsF8tY5CFFOtC22tFUXictIZGwVDXyOpg=,tag:9XJDWT+wrMlmMM25ONTJ9A==,type:str]
    version: 3.13.3
