apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:fda5Va9bsnY=,iv:gEi9aXa5f0WjYhBU6Q8J0zuJaMFE1Kux3UM88wQNdIU=,tag:s2dMDRlAF7bC8tIq2rbOtg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:mvbg1gT/9w8da9E/0ffWXA==,iv:sJ3Tn5/JKboq9Ph6AHbFUjNwvZTrAt5fKXk1HhedbpY=,tag:h1rcEJqWkFyH7Qjsi3t29w==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHFVNTlMNHRaUkxFTDNL
            UHQzeXJjdWY2bktzZEdkdFdOQXQwbXhKd0ZRCncxM2Z3RCtPb1pHY2swWWdPbDNS
            aG5pTDJReTFzMnJLOFBwT1d5Y1lGbUEKLS0tICsydm9FZGlRZG4xeFNjK3FqT3pr
            QVJQK2svcWwzaFl3aWJnMmZuK3kweEEKe9kC+3S1HBjGXJU+o9YmfNGN8Kb+ghwz
            E8/aHI2Mj2kWfXOW0CxcKBlkxEY3wevAhDykKlGIP99v0q2lIQXNcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T10:35:35Z"
    mac: ENC[AES256_GCM,data:ahLkw0aq7Wql1oSW0r28mfTD9e7SItXmKPpHaVVSTWCfVX0CnYXkIL1+2Ipr0HCm1I57xZDSYgegw9ES0JkUbhikSDuHsdhCUxPFBzX+qtS+4JWyZEn8xmgVxvWSTJGwW1EMOe03QvzYqWYdIraBRM3OzhMwUALatSSWaGuCnv0=,iv:PubFAN/7a7w3ZlmR4hbvRw73liOIsfLA2UtBQuUe09c=,tag:E9n4Tv9ph5gb3HPFGAXqFg==,type:str]
    version: 3.13.3
