apiVersion: v1
data:
    password: ENC[AES256_GCM,data:O7MWnvDl7VuN3BZ3VMVhlA==,iv:IqrM5k98kO6etdyf0Kb5gE1WcqVDnHRZYrbb93gojew=,tag:Ax4QkI+mnfl/ZaAR9zFlzw==,type:str]
    user: ENC[AES256_GCM,data:LqhW8Z10+zQ=,iv:RImRCr1jlCNW1ld73Vw1ugX6idTRpgVLGeEC0STHgQ4=,tag:fqX77C+MGzBeOJh6PfpSRQ==,type:str]
kind: Secret
metadata:
    name: linkding-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzJVdlNDWWJwZXN4WEdv
            cmxUeTJBYzFaSU4zT0d3NEZuUWRaVUx3OUFvClRkeFVzaW82em02ZkxaQnFUQkJO
            bGlPWXVRVEhyazc2YVJybFBIV3lyNm8KLS0tICtoMzluTlUrVld3cDlPSHFQMWsx
            cE1HcUgwWnJWeXFiWFNwUzN5WnRlcjAKtbWT1FWb5jniHI5IhLmTMbN3fuqP2YqB
            9NWgMvKgJ8SPk3W+aXoTumBh71Be1mgUlep92VDkiHjRR4JhFIT/SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T10:19:44Z"
    mac: ENC[AES256_GCM,data:ncczwza9eXd9zqyz4dNWl8q3kZw7uqsL81XjN1rMmYNPoTPNxkmDYDnI5HMmUi128xizIDf1Zhvy8zZeupSWinfiVOm5OzOtiD5X+NU2CRK5vN6ERCDJCGElEmUF9gDUdzKEvS6yp0vzRvTUF/YzZbFDQL4VRAv2mXeO5ZSV8io=,iv:SAkIRI9TmhE+2EaRc3Fr65eIibi977Ei3lSfznFNhT4=,tag:Q3CfAbu3pzv0YEPvn+d8HQ==,type:str]
    version: 3.13.3
