apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:zHhRusmyi3U=,iv:Si2wzx2GUZCJjMfQ+SqXtDKqJvttZUS5qBRHl/aoVGM=,tag:wdym+FA9z2rYFfqKHfma5A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:574bcncgmrpGaV3VFCvugQ==,iv:p+kZFmN7s+OAidbXsiyU+xJFL4rxiV9vpa/SDOK0ubg=,tag:fqd3QNg5RsDlRg0c65fU1Q==,type:str]
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR3RlczY3RDZVL1NsZXJB
            b1lJckdieDhST2xrRjRyY0ZpNTZ3TXZxWkRrCmR3STVLQStVZ3RxMlIzSWZLemd1
            ckNoQzZRdk1lNTRFV0tHQ0hYM2ZsWjQKLS0tIDhQRjdqbU5NZ2IybkRyNVJIeG90
            UWtZQ3BOQjR5VWVHTkgwbG5iMm5mRlkK9Igtb5DX+i+sIg78ExOgPfM93snBvnPr
            +TgTkbvm8JueGHt7PWeYC/oxs1DDNpe/Ve57GnOgV/3yuIZeKdIifw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T11:22:38Z"
    mac: ENC[AES256_GCM,data:vrJcli8gXmO1m4FuauUpf2JTzyJpkB+o03CL+CbZDprrsGx4yO9aBcTqsLEL6yd+X2cJxNOE1QXgeehet1jk4SzaXrsnZiHas33IxZGMb2DQY9dIQgopUDsywa3b+UHom7+FSVri2M+jDkJnlL+qygI8YFhnS0C2QCYACvvfnyk=,iv:eRFL58RiArhorO0v4Ts9mMmjXJRL1osSWWmX3KnpsVE=,tag:ZuT2N8AkHlI7wGLiO3X/0w==,type:str]
    version: 3.13.3
