apiVersion: v1
kind: Secret
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:eweJSpM=,iv:70UJXVbJtQ1rH59ECICHiMfw8rCB3hd6jgzQtkSHhw4=,tag:fdW1b3UaHi+tBuwW+ZzPpw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:22z3qu1XMk06bjo=,iv:Sr3T+RJDr0Xb6aCD1GkcUJHmrKLxRnq3swtCO00JXOo=,tag:E2R5TWBG1o9OiArvBAi0Sg==,type:str]
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc3RtRSs4c3ZEbG52Q0ZG
            MXpiQVBRL0k0NHVxbzRwc0xhWFJnRG9oZFhvCmhwL3gvZ2RwV0grSVVGMnNkdHh2
            Z0w0bmo0QzF3NWRKOXNOODFESVRmUGsKLS0tIDNKTDNBOEdXOHdFNUZ1UXp6Ykgy
            VnE0bC9mYjlaV0UyMEFYN0tyeVpFM00K/7MODwno60YQTXpyU84MGMlewG8/iD8K
            u22Epyf8EMEnUwVoO2BEzZ1y9w05mt4GoeY3a+oJeXY/2Z+8TDADDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T10:32:06Z"
    mac: ENC[AES256_GCM,data:9fqsRqRfXVEwou7juNRwEPCt80lxA5pRQGvwowFpnGf/+j1y9gmhS2qhAidOnPwZWeVzpjt5K2ZrSokeuXsJMQUVunWJDyJLA7EWyxBbXd+wJ1Dlthr7WwsYoUnK6y7K35u8Mpa9b8wQYyPCIJK9VbWEe7TNQZyo+HwLyTKC7cM=,iv:qUc949qBdxIXnKCSADgjQkhh23D4HdAQXNaVYzs6cCg=,tag:q6HRUtNy3WUEczZYKJ4pQw==,type:str]
    version: 3.13.3
