apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OC8oKwQjGy4=,iv:xm6EeRDogUW/P5itmxWrTcZSijRRko1yqYSw9ztCL0k=,tag:A++yOjTYeNXPZJRDSZg5TA==,type:str]
    user: ENC[AES256_GCM,data:E5qJyPrGZfQ=,iv:uyhb7mOVi3+0BYJwlIU2DbnbM+hZ4Mqoxm+JID1Ccxc=,tag:PPdUrbFGY/hV8091uH9GsQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b3c2MWh3Nm9nd1RjZmh2
            bHZkbEdOQi9WbVU3VUI5cmZ6ZkVEY0RIRkEwCklwMEJXbnlyd0xPZEtFMEJlQVZI
            R3dOLzU3eDBLd25LaGk1VkdCd0VRd00KLS0tIHJpVlRmRlhUK1R2OW5pd0l2c1pN
            VTQ1T1VsdUFDSE5OMHdKWDJUYnRrWUkK7P3rAUJ5Ato725WS519dTS1vBKHW0crh
            S/6+XtAcQDak5Wx86dEUgeOXKyJt7p4coZM2j8nnCErmn05xuNkpdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T07:34:26Z"
    mac: ENC[AES256_GCM,data:gBbfzVSDxUe78zoeM8TynbanP6X6/oSGzIFEX9xBNXM6P0y20gK66+PVsJZapDCKSoj+Um7qzB+DFPaOjsdsfigI/gdiJIoq8TSgF6SIfF8JQmqBID1/GnMUHNCvzr905GLMMR1xioM3B0ToggXzK8Cqps9guqqkoY7sxpDUQfg=,iv:wQ/MH6r6Blh1/K93jrKa27TM6Ma8QszE6QASvVqyrSU=,tag:Hr/pncJtYllVtAsV3nZe4Q==,type:str]
    version: 3.13.3
