apiVersion: v1
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:5ljMA9pN42p6pOzib1Y4QiVGdfiD+nz9GOISUPeAsZFIeYn0dNanqhW2ocsVx2sawzCh4CWKRTz7NOaies9QHNAc3szwS+EXqCOHeXny7o+8xpyOIRd2bmNJAhwzHuQpIvnT1SviVKioWx4FV+59MAZMQQM=,iv:2oYA4eaU3I7n6p/iwg995i7BhrmcccJ0VVktdH+uy20=,tag:sEp/caUlhAHabxsoQ9+GfA==,type:str]
kind: Secret
metadata:
    name: paperless-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyKzdJRVBpQWJjWE1BVGlD
            Z1grTm1WMTlhOVVxM1hkdDJtTExrU0dlUG1nCno4c2JxZVBjbitjVGY1NW40ZnFa
            Z1ZYVnZsTDJnckorcjhzWjVzaWZmMjgKLS0tIGhINVdDOTVra0M1N1NJanJIaVJk
            YUh1MGlaQU9oMW9SUWNSSjlkVXhHV28K3N2bpsjka7hjAkCSWFe7AmkRQK7eDSSi
            SKwY3KxGeLZxRjlGN5A6EYsSx0lQ/0Eb4gMNPpXsevS+PgyuKyJlnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wjgfg00l3yy6mlxmg4nhz59kguqjaf58jdn2hddya34lcxwgaggqejc095
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T07:16:29Z"
    mac: ENC[AES256_GCM,data:Qxf7EPZvYUQszWnHvuuX4tJhkmJp4LDUP+4KrGwAolU7SCrmOdwNCgSdQ7EV9YedF2a2xOteO4joo/kHP4CcxtRvbnFDkP5r2Plvq0CDoqC+4y1QZ/naHluVlnHb7UAPFW4C79iFpmTDZtJo2B16gDHwySt/FrkrDGEAirRS8us=,iv:MSQXC/i9YD3voHti+4YxAbgjAVG4RTaq3ruLltd9n7s=,tag:awB5CGBNktaoghC4J29KSg==,type:str]
    version: 3.13.3
